version: "3.1"
services:

  redis:
    image: bitnami/redis:5.0.5
    hostname: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: template
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: template
    ports:
      - 54320:5432
    volumes:
      - ./data:/var/lib/postgresql/data
